apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: pedidos-veloz
type: Opaque
stringData:
  # O Kubernetes aceita o formato stringData para injetar valores limpos de forma segura
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "SenhaSegura123"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pedidos-veloz
data:
  # Dados que não são secretos, como o endereço do banco de dados
  DB_HOST: "postgres-db-service"
  DB_NAME: "loja_veloz"
